export default {
  insTagGenerator: {
    seoDesc: "Saupoudrez un peu de magie virale sur vos publications Instagram avec ce générateur de hashtag IA gratuit de Shulex ! Améliorez votre présence sur les réseaux sociaux.",
    seoTitle: "Générateur de hashtag Instagram gratuit - Shulex VOC",
    title: "Générateur de hashtag Instagram gratuit",
    titleText1: {
      subtitle: "Les hashtags sont un outil essentiel pour améliorer la visibilité et la portée de votre contenu sur les plateformes de médias sociaux, en particulier les plateformes de contenu principal comme Instagram et Youtube. En modifiant stratégiquement les hashtags qui correspondent à votre contenu, vous pouvez augmenter de façon exponentielle vos chances de créer une sensation virale. Les hashtags viraux, tels que #SidhuMoosewala, #SidhuMoosewalaFans, #MooseTape et #MoosewalaArmy, peuvent attirer les fans de l'artiste concerné et faire en sorte que les contenus générés par les utilisateurs se répandent largement.  Il est donc très important de trouver un bon hashtag. Le générateur de hashtag peut rendre moins pénible la création d'effets de hashtag.",
      title: "Qu'est-ce que le générateur de hashtags ?"
    },
    titleText2: {
      subtitle: "Notre générateur de hashtags Instagram piloté par l'IA s'appuie sur l'intelligence artificielle (IA) pour créer des hashtags Instagram adaptés à vos besoins uniques. Comme plusieurs autres outils d'IA que nous proposons gratuitement, il est piloté par ChatGPT 4, un modèle de langage large hautement intelligent (également connu sous le nom de chatbots) capable de s'engager dans des conversations qui ressemblent à des interactions humaines. En outre, notre générateur de légendes pour les médias sociaux, alimenté par ChatGPT, est une ressource précieuse que vous devriez certainement conserver pour une utilisation future.",
      title: "Comment fonctionne ce générateur de hashtag Instagram ?"
    },
    videoTitle: "Comment utiliser notre générateur de hashtag Instagram"
  },
  shopifyStores: {
    cards: "Marques de cartes activées",
    country: "Pays",
    description: "Description",
    domain: "Domaine",
    name: "Nom",
    province: "Province",
    search: "Rechercher un nom",
    seoDesc: "Espionnez les concurrents Shopify, les produits les plus vendus, les plus tendances et gagnants, les thèmes Shopify, les applications, les magasins à la croissance la plus rapide, les produits nouvellement lancés, le dropshipping et plus encore par Shulex VOC.",
    seoTitle: "Shopify Stores List - Shulex VOC Meilleur outil Ecommerce AI",
    title: "Liste des magasins Shopify",
    total: "Total des enregistrements"
  },
  socialMediaGenerator: {
    seoDesc: "Créez facilement des légendes parfaites pour Facebook, Instagram, Twitter et Linkedin en quelques secondes avec ce générateur de légendes IA gratuit pour les réseaux sociaux de Shulex.",
    seoTitle: "Générateur de sous-titres IA gratuit pour les médias sociaux - Shulex VOC",
    title: "Générateur de légendes gratuit pour les réseaux sociaux",
    titleText: {
      subtitle: "En tant qu'acteur des médias sociaux, il vous arrive souvent de devoir trouver une légende pour un post sur les médias sociaux, ce qui peut être ennuyeux car vous n'avez pas toujours l'inspiration nécessaire pour faire le travail.  Cet incroyable générateur de posts sur les médias sociaux va révolutionner votre processus de création de calendrier de contenu. Non seulement il rationalisera l'aspect rédactionnel de votre travail, mais il vous aidera également à générer des idées de hashtags et de mots-clés, augmentant ainsi la visibilité de vos posts auprès d'un public plus large. En outre, vous pouvez utiliser cet outil pour reformuler et améliorer vos légendes existantes sans effort. Il vous suffit de saisir votre légende actuelle et de regarder l'outil la transformer sans effort en un élément de contenu captivant. Avec cet outil à vos côtés, c'est comme si vous disposiez d'un assistant de rédaction compétent qui connaît bien les algorithmes, travaille à un rythme accéléré et est toujours disponible pour vous aider à chaque fois que vous en avez besoin. Adoptez cet outil qui change la donne et améliorez votre calendrier de médias sociaux avec une pléthore de posts générés par l'IA.",
      title: "Vous avez du mal à trouver des sous-titres ?"
    }
  },
  tipChatbot: {
    check: "Vérifier ce qui suit",
    content: "Essayez notre Chatbot IA qui peut résoudre automatiquement 80% des commentaires de vos clients.",
    title: "Vous vous sentez épuisé par le service à la clientèle ?"
  },
  ttCaptionGenerator: {
    seoDesc: "Créez facilement des sous-titres parfaits pour Tiktok en quelques secondes avec ce générateur de sous-titres Tiktok AI gratuit de Shulex.",
    seoTitle: "Générateur de sous-titres AI gratuit pour Tiktok - Shulex VOC",
    title: "Générateur de légendes Tiktok gratuit",
    titleText: {
      subtitle: "En tant qu'acteur des médias sociaux, il vous arrive souvent de devoir trouver une légende pour un post sur les médias sociaux, ce qui peut être ennuyeux car vous n'avez pas toujours l'inspiration nécessaire pour faire le travail.  Cet incroyable générateur de posts sur les médias sociaux va révolutionner votre processus de création de calendrier de contenu. Non seulement il rationalisera l'aspect rédactionnel de votre travail, mais il vous aidera également à générer des idées de hashtags et de mots-clés, augmentant ainsi la visibilité de vos posts auprès d'un public plus large. En outre, vous pouvez utiliser cet outil pour reformuler et améliorer vos légendes existantes sans effort. Il vous suffit de saisir votre légende actuelle et de regarder l'outil la transformer sans effort en un élément de contenu captivant. Avec cet outil à vos côtés, c'est comme si vous disposiez d'un assistant de rédaction compétent qui connaît bien les algorithmes, travaille à un rythme accéléré et est toujours disponible pour vous aider à chaque fois que vous en avez besoin. Adoptez cet outil qui change la donne et améliorez votre calendrier de médias sociaux avec une pléthore de posts générés par l'IA.",
      title: "Vous avez du mal à trouver des sous-titres ?"
    }
  },
  ttHashtag: {
    seoDesc: "Saupoudrez un peu de magie virale sur vos publications Tiktok avec ce générateur de hashtag IA gratuit de Shulex ! Améliorez votre présence sur les réseaux sociaux.",
    seoTitle: "Générateur de hashtag Tiktok gratuit - Shulex VOC",
    title: "Générateur de hashtag Tiktok gratuit",
    titleText1: {
      subtitle: "Les hashtags sont un outil essentiel pour améliorer la visibilité et la portée de votre contenu sur les plateformes de médias sociaux, en particulier les plateformes de contenu principal telles que Tiktok et Youtube. En modifiant stratégiquement les hashtags qui correspondent à votre contenu, vous pouvez augmenter de façon exponentielle vos chances de créer une sensation virale. Les hashtags viraux, tels que #SidhuMoosewala, #SidhuMoosewalaFans, #MooseTape et #MoosewalaArmy, peuvent attirer les fans de l'artiste concerné et faire en sorte que le contenu généré par l'utilisateur se répande largement.  Il est donc très important de trouver un bon hashtag. Le générateur de hashtag peut rendre moins pénible la création d'effets de hashtag.",
      sybtitle: "Les hashtags sont un outil essentiel pour améliorer la visibilité et la portée de votre contenu sur les plateformes de médias sociaux, en particulier les plateformes de contenu principal telles que Tiktok et Youtube. En modifiant stratégiquement les hashtags qui correspondent à votre contenu, vous pouvez augmenter de façon exponentielle vos chances de créer une sensation virale. Les hashtags viraux, tels que #SidhuMoosewala, #SidhuMoosewalaFans, #MooseTape et #MoosewalaArmy, peuvent attirer les fans de l'artiste concerné et faire en sorte que le contenu généré par l'utilisateur se répande largement.  Il est donc très important de trouver un bon hashtag. Le générateur de hashtag peut rendre moins pénible la création d'effets de hashtag.",
      title: "Qu'est-ce que le générateur de hashtags ?"
    },
    titleText2: {
      subtitle: "Notre générateur de hashtags Tiktok piloté par l'IA tire parti de l'intelligence artificielle (IA) pour créer des hashtags Tiktok adaptés à vos besoins uniques. Comme plusieurs autres outils d'IA que nous proposons gratuitement, il est piloté par ChatGPT 4, un modèle de langage large hautement intelligent (également connu sous le nom de chatbots) capable d'engager des conversations qui ressemblent à des interactions humaines. En outre, notre générateur de légendes pour les médias sociaux, alimenté par ChatGPT, est une ressource précieuse que vous devriez certainement conserver pour une utilisation future.",
      title: "Comment fonctionne ce générateur de hashtag Tiktok ?"
    }
  },
  ttUsername: {
    seoDesc: "Créez une identité en ligne unique avec le Tiktok Username Generator de Shulex VOC. Trouvez votre nom d'utilisateur idéal et renforcez votre présence en ligne dès aujourd'hui !",
    seoTitle: "Générateur de nom d'utilisateur Tiktok gratuit - Shulex VOC",
    title: "Générateur de nom d'utilisateur Tiktok gratuit",
    titleText1: {
      subtitle: "Un générateur de nom d'utilisateur est un outil qui génère rapidement une compilation de pseudos sur les réseaux sociaux en utilisant les informations fournies par les utilisateurs. Notre outil incorpore la puissance de l'intelligence artificielle (IA) avec l'aide des utilisateurs pour produire de nombreux pseudos créatifs et agréables en quelques secondes. Obtenez une liste complète de pseudos pour diverses plateformes telles qu'Instagram, TikTok, YouTube, Pinterest, Roblox, etc. Lorsque les utilisateurs saisissent quelques termes descriptifs qui reflètent leur identité et leurs passions, le générateur génère une gamme d'options qui capturent vraiment leur personnalité unique.",
      title: "Qu'est-ce qu'un générateur de noms d'utilisateur ?"
    },
    titleText2: {
      subtitle: "Ce générateur de noms d'utilisateur AI est spécialement conçu pour éliminer l'incertitude lorsqu'il s'agit de créer des noms d'utilisateur pour diverses plates-formes en ligne. Que vous rejoigniez des forums en ligne ou des plateformes de jeux, cet outil vous fera gagner un temps précieux et un effort mental en vous fournissant des noms d'utilisateur uniques et personnalisés. Vous n'aurez plus à vous battre pour trouver des noms d'utilisateur accrocheurs et mémorables lorsque vous vous inscrivez sur de nouveaux sites ou lorsque vous changez votre personnalité en ligne.<h3 style=\"color:#1d2129\">Plateformes de médias sociaux</h3>L'aspect le plus remarquable de notre générateur de noms d'utilisateur est sa capacité à générer rapidement des idées de noms d'utilisateur pour les médias sociaux. En quelques secondes, vous pouvez trouver un nouveau pseudo pour une variété de plateformes, y compris Instagram, Twitter, TikTok, Tumblr, YouTube, BeReal, Snapchat, Mastodon, Twitch, et de nombreux autres sites Web qui exigent l'enregistrement de pseudos. Profitez de la commodité de trouver la poignée parfaite pour vos plateformes en ligne préférées en un rien de temps.",
      title: "A quoi peut servir ce générateur de noms d'utilisateur ?"
    }
  },
  unitConverter: {
    articles: {
      content1: "Vous cherchez un outil de conversion d'unités fiable pour votre commerce électronique ? Ne cherchez pas plus loin que Unit Convert ! Notre outil facilite la conversion entre différentes unités de mesure, notamment la longueur, le poids, le volume, etc. Avec Unit Convert, vous pouvez vous assurer que vos listes de produits sont exactes et cohérentes, ce qui peut contribuer à améliorer la satisfaction des clients et à réduire les retours. De plus, notre interface conviviale et nos conversions précises rendent l'utilisation facile, même pour ceux qui ne sont pas familiers avec les conversions d'unités. Alors, pourquoi attendre ? Essayez Unit Convert dès aujourd'hui et voyez comment il peut vous aider à rationaliser vos opérations de commerce électronique et à améliorer vos résultats ! Si vous avez besoin de convertir des unités de mesure, il existe de nombreux outils pour vous aider. L'une des options les plus populaires est Unit Convert Pro, qui peut tout gérer, de la longueur au poids en passant par la conversion des unités de viscosité. Grâce à cet outil, vous pouvez facilement convertir des unités de mesure en quelques clics. Que vous ayez besoin de convertir des unités de mesure pour le travail ou juste pour le plaisir, il est facile de convertir des unités de mesure avec les bons outils. Pourquoi ne pas essayer unit convert dès aujourd'hui et voir comment il peut vous aider à convertir des unités de mesure rapidement et facilement ? Trouvez notre convertisseur d'unités dans Google.",
      content2: "Vous pouvez : convertir 150 g en unité kg. convertissez 0,15 m en unité cm. convertir 30 ml en unité l.",
      content3: "<a href=\"https://www.voc.ai\" target=\"_blank\">VOC AI INC. (Shulex VOC)</a> Boostez votre business avec l'outil ChatGPT n°1. Nous analysons les commentaires pour aider à construire des produits gagnants dans le commerce électronique. Si vous voulez en savoir plus, visitez : <a href=\"https://www.voc.ai\" target=\"_blank\">https://www.voc.ai</a> Notre extension de navigateur : <a href=\"https://www.voc.ai/tools/chatgpt-for-amazon\" target=\"_blank\"> https://www.voc.ai/tools/chatgpt-for-amazon</a>",
      content4: "Dans le passé, différents systèmes d'unités ont été utilisés, qui sont définis comme un ensemble d'unités de mesure avec des règles qui les relient les unes aux autres. Une unité de mesure est une grandeur spécifique d'une quantité qui sert d'étalon pour mesurer le même type de quantité, comme la longueur, le poids et le volume. Auparavant, des systèmes de mesure locaux étaient établis, qui pouvaient être basés sur des facteurs arbitraires tels que la longueur du pouce d'un roi. Bien que cela puisse fonctionner au niveau local, cela rend l'interaction difficile lorsqu'il s'agit de commerce et de science, car d'autres personnes peuvent ne pas être en mesure de comprendre les unités ou de s'y référer. C'est pourquoi des systèmes plus universels et plus cohérents ont été développés au fil du temps. Aujourd'hui, le système métrique, le système impérial et les unités coutumières des États-Unis sont quelques-uns des systèmes d'unités utilisés. Le système international d'unités (SI) est le système métrique standard actuellement utilisé. Il se compose de sept unités de base SI : la longueur, la masse, le temps, la température, le courant électrique, l'intensité lumineuse et la quantité de substance. Bien que le SI soit presque universellement utilisé dans les sciences, certains pays, comme les États-Unis, utilisent encore leur propre système d'unités. Cela s'explique en partie par les coûts financiers et culturels considérables qu'implique le changement d'un système de mesure par rapport aux avantages potentiels de l'utilisation d'un système normalisé. Par conséquent, l'utilisation quotidienne de l'USC est encore répandue aux États-Unis, et de nombreux convertisseurs d'unités, y compris ce calculateur de conversion, existent pour s'assurer que les gens du monde entier peuvent communiquer des mesures différentes de manière efficace.",
      content5: "Au cours des VIIIe et IXe siècles de l'ère commune (CE), la civilisation arabe a prospéré au Moyen-Orient et en Espagne. Les Arabes utilisaient les pièces comme unité de mesure du poids, car une pièce frappée ne pouvait pas être facilement coupée ou rasée pour réduire son poids, fournissant ainsi une norme mesurable. Ils ont utilisé un dirhem en argent comme mesure de base du poids, ce qui équivalait à peu près à 45 grains d'orge adultes. Dix dirhèmes constituaient un Wukryeh, qui a été traduit en latin par « uncia », d'où le mot « once ». Le commerce s'est finalement étendu de la région méditerranéenne à l'Europe, y compris aux cités-États du nord de l'Allemagne. En conséquence, une livre, qui équivalait à 16 onces d'argent ou 7 200 grains, est devenue une mesure couramment utilisée dans de nombreuses régions. Bien que l'Angleterre ait également adopté cette mesure, une pénurie d'argent a amené le roi Offa à réduire la mesure de la livre à 5 400 grains pour utiliser des pièces plus petites. Lorsque Guillaume le Conquérant est devenu roi d'Angleterre, il a conservé la livre de 5 400 grains pour frapper des pièces, mais est revenu à la livre de 7 200 grains à d'autres fins. Alors que de nombreux pays ont utilisé la livre à partir de cette époque, y compris l'Angleterre (la livre sterling britannique, ou GBP, équivalait à une livre d'argent à l'époque du roi Offa), le système de poids avoirdupois a été adopté sous le règne de la reine Elizabeth au XVIe siècle. Il s'agissait d'un système basé sur le poids du charbon et son nom était dérivé de l'expression française « avoir de pois » (marchandises de poids ou de propriété). L'avoirdupois équivalait à 7 000 grains, 256 drams de 27,344 grains chacun, soit 16 onces de 437 ½ grains chacun. Depuis 1959, la livre avoirdupois est officiellement définie dans la plupart des pays anglophones comme étant 0,45359237 kilogramme. Différents systèmes de mesure se sont également développés au fil du temps dans les pays asiatiques. Par exemple, dans l'Inde ancienne, une mesure de poids appelée « Satamana » était utilisée, qui équivalait au poids de 100 baies de gunja. En Chine, le premier empereur Shi Huang Di a créé un système de poids et mesures au IIIe siècle avant notre ère (avant l'ère commune). La mesure du poids était basée sur le navire, qui équivalait à environ 132 livres. Le Chi et le Zhang étaient des unités de longueur équivalentes à environ 25 centimètres (9,8 pouces) et 3 mètres (9,8 pieds), respectivement. Les Chinois ont également développé un moyen de garantir la précision en utilisant un bol de taille spéciale utilisé pour les mesures qui émettaient également un son spécifique lorsqu'il était frappé : si le son était décalé, la mesure n'était pas précise.",
      content6: "En 1668, John Wilkins a proposé un système décimal reliant la longueur, la surface, le volume et la masse sur la base d'un pendule dont l'unité de base de longueur était un battement d'une seconde. Gabriel Mouton a proposé un système décimal en 1670 basé sur la circonférence de la Terre, une idée soutenue par d'autres scientifiques éminents de l'époque tels que Jean Picard et Christiaan Huygens, mais elle ne s'est pas concrétisée pendant environ 100 ans. Au milieu du XVIIIe siècle, il était clair pour les nations qui échangeaient et échangeaient des idées scientifiques que la normalisation des poids et des mesures était nécessaire. En 1790, Charles Maurice de Talleyrand-Périgord, prince de Talleyrand, a proposé aux Britanniques (représentés par John Riggs-Miller) et aux Américains (représentés par Thomas Jefferson) de définir une norme commune de longueur basée sur la longueur d'un pendule. La même année, Thomas Jefferson a présenté le « Plan pour établir l'uniformité dans la monnaie, les poids et les mesures des États-Unis », qui préconisait un système décimal dans lequel les unités étaient liées les unes aux autres par des puissances de dix. Un comité formé en France et composé de certains des plus éminents scientifiques de l'époque est parvenu à la même conclusion et a également proposé un système décimal pour tous les poids et mesures. Bien que le Congrès ait examiné le rapport de Jefferson, il n'a pas été adopté. En Grande-Bretagne, John Riggs-Miller a perdu son siège au Parlement britannique lors des élections de 1790. En tant que tel, le système de mesure n'a été mis en œuvre qu'en France et, en 1795, le système métrique a été officiellement défini dans la loi française. Cependant, ce n'est qu'en 1799 que le système métrique a été officiellement adopté en France, même s'il n'était toujours pas universellement observé dans tout le pays. La diffusion du système métrique n'a pas été rapide et les régions annexées par la France sous le règne de Napoléon ont été les premières à adopter le système métrique. En 1875, les deux tiers de la population européenne et près de la moitié de la population mondiale avaient adopté le système métrique. En 1920, environ 22 % de la population mondiale utilisait le système impérial ou le système coutumier américain, 25 % utilisant principalement le système métrique et 53 % n'utilisant aucun des deux. Le Système international d'unités, actuellement le système de mesure le plus utilisé, a été publié en 1960. Il a été adopté par tous les pays développés à l'exception des États-Unis, bien que, comme mentionné précédemment, il soit largement utilisé dans les sciences et dans l'armée, même aux États-Unis.",
      title1: "Que peut faire cet outil ?",
      title2: "Exemples",
      title3: "Qui sommes nous?",
      title4: "Différents systèmes d'unités",
      title5: "Histoire de la livre",
      title6: "Bref historique du système métrique"
    },
    seoDesc: "Ce calculateur gratuit de conversion d'unités permet de convertir les unités courantes de longueur, de poids par Shulex VOC.",
    seoTitle: "Outil gratuit de conversion d'unités - Shulex VOC",
    title: "Outil de conversion d'unités gratuit"
  },
  usernameGenerator: {
    seoDesc: "Créez une identité en ligne unique avec le générateur de nom d'utilisateur de Shulex VOC. Trouvez votre nom d'utilisateur idéal et renforcez votre présence en ligne dès aujourd'hui !",
    seoTitle: "Générateur de nom d'utilisateur gratuit - Shulex VOC",
    title: "Générateur de nom d'utilisateur gratuit",
    titleText1: {
      subtitle: "Un générateur de nom d'utilisateur est un outil qui génère rapidement une compilation de pseudos sur les réseaux sociaux en utilisant les informations fournies par les utilisateurs. Notre outil incorpore la puissance de l'intelligence artificielle (IA) avec l'aide des utilisateurs pour produire de nombreux pseudos créatifs et agréables en quelques secondes. Obtenez une liste complète de pseudos pour diverses plateformes telles qu'Instagram, TikTok, YouTube, Pinterest, Roblox, etc. Lorsque les utilisateurs saisissent quelques termes descriptifs qui reflètent leur identité et leurs passions, le générateur génère une gamme d'options qui capturent vraiment leur personnalité unique.",
      title: "Qu'est-ce qu'un générateur de noms d'utilisateur ?"
    },
    titleText2: {
      subtitle: "Ce générateur de noms d'utilisateur AI est spécialement conçu pour éliminer l'incertitude lorsqu'il s'agit de créer des noms d'utilisateur pour diverses plates-formes en ligne. Que vous rejoigniez des forums en ligne ou des plateformes de jeux, cet outil vous fera gagner un temps précieux et un effort mental en vous fournissant des noms d'utilisateur uniques et personnalisés. Vous n'aurez plus à vous battre pour trouver des noms d'utilisateur accrocheurs et mémorables lorsque vous vous inscrivez sur de nouveaux sites ou lorsque vous changez votre personnalité en ligne. <h3 style=\"color:#1d2129\">Plateformes de médias sociaux</h3> L'aspect le plus remarquable de notre générateur de noms d'utilisateur est sa capacité à générer rapidement des idées de noms d'utilisateur pour les médias sociaux. En quelques secondes, vous pouvez trouver un nouveau pseudo pour une variété de plateformes, y compris Instagram, Twitter, TikTok, Tumblr, YouTube, BeReal, Snapchat, Mastodon, Twitch, et de nombreux autres sites Web qui exigent l'enregistrement de pseudos. Profitez de la commodité de trouver la poignée parfaite pour vos plateformes en ligne préférées en un rien de temps.",
      title: "A quoi peut servir ce générateur de noms d'utilisateur ?"
    }
  }
};
