/* eslint-disable react/no-unescaped-entities */
import { generateHrefLangConfig } from 'components/Header/mod/HrefLang';
import { SITE_WITH_PORTAL } from '@/constant/base';
import Script from 'next/script';
import styles from './index.module.scss';

const BASE_HOST = 'solvea.cx';

export const metadata = {
  title: 'Privacy Policy | Solvea',
  description: 'Solvea Privacy Policy',
  alternates: generateHrefLangConfig('/privacy-policy', undefined, SITE_WITH_PORTAL),
};

function TermsAndCondition() {
  return (
    <>
      <Script src="https://accounts.google.com/gsi/client" strategy="afterInteractive" />

      <div className={styles.content}>
        <h1>Privacy Policy</h1>
        <p>
          <strong>Updated at 2024-06-11</strong>
        </p>
        <div>
          <div>
            <div>
              <p>
                <br />
                Solvea (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy
                Policy explains how your personal information is collected, used, and disclosed by
                Solvea. It also describes your choices regarding use, access, and correct of your
                personal information.
              </p>
              <p>
                <br />
                This Privacy Policy applies to our website, and its associated subdomains
                (collectively, our “Service”) alongside our application, Solvea. By accessing or
                using our Service, you signify that you have read, understood, and agree to our
                collection, storage, use, and disclosure of your personal information as described
                in this Privacy Policy and our Terms of Service. The use of information collected
                through the Service is limited to the purpose providing the Service for which our
                client has engaged Solvea.
              </p>
              <h2>
                <strong>
                  <br />
                  Definitions and Key Terms
                </strong>
              </h2>
              <p>
                To help explain things as clearly as possible in this Privacy Policy, every time any
                of these terms are referenced, are strictly defined as:
              </p>
              <p>
                1.&nbsp;Cookie: small amount of data generated by a website and saved by your web
                browser. It is used to identify your browser, provide analytics, remember
                information about you such as your language preference or login information.
              </p>
              <p>
                2.&nbsp;Company: when this policy mentions “Company,” “we,” “us,” or “our,” it
                refers to Solvea LIMITED, 160 E Tasman Drive Suite 202 San Jose, CA, 95134. that is
                responsible for your information under this Privacy Policy.
              </p>
              <p>
                3.&nbsp;Country: where Solvea or the owners/founders of Solvea are based, in this
                case is Hong Kong
              </p>
              <p>
                4.&nbsp;Customer: refers to the company, organization or person that signs up to use
                the Solvea Service to manage the relationships with your consumers or service users.
              </p>
              <p>
                5.&nbsp;Device: any internet connected device such as a phone, tablet, computer or
                any other device that can be used to visit Solvea and use the services.
              </p>
              <p>
                6.&nbsp;IP address: Every device connected to the Internet is assigned a number
                known as an Internet protocol (IP) address. These numbers are usually assigned in
                geographic blocks. An IP address can often be used to identify the location from
                which a device is connecting to the Internet.
              </p>
              <p>
                7.&nbsp;Personnel: refers to those individuals who are employed by Solvea or are
                under contract to perform a service on behalf of one of the parties.
              </p>
              <p>
                8.&nbsp;Personal Data: any information that directly, indirectly, or in connection
                with other information — including a personal identification number — allows for the
                identification or identifiability of a natural person.
              </p>
              <p>
                9.&nbsp;Service: refers to the service provided by Solvea as described in the
                relative terms (if available) and on this platform.
              </p>
              <p>
                10.&nbsp;Third-party service: refers to advertisers, contest sponsors, promotional
                and marketing partners, and others who provide our content or whose products or
                services we think may interest you.
              </p>
              <p>
                11.&nbsp;Website: Solvea."'s" site, which can be accessed via these URLs(splited by
                comma): solvea.cx, {BASE_HOST}
              </p>
              <p>
                12.&nbsp;You: a person or entity that is registered with Solvea to use the Services.
              </p>
              <h2>
                <strong>&nbsp;</strong>
              </h2>
              <h2>
                <strong>What Information Do We Collect?</strong>
              </h2>
              <p>
                We collect information from you when you visit our website/app, register on our
                site, place an order, subscribe to our newsletter, respond to a survey or fill out a
                form.
              </p>
              <p>1.&nbsp;Name / Username</p>
              <p>2.&nbsp;Phone Numbers</p>
              <p>3.&nbsp;Email Addresses</p>
              <p>4.&nbsp;Mailing Addresses</p>
              <p>5.&nbsp;Job Titles</p>
              <p>6.&nbsp;Billing Addresses</p>
              <p>7.&nbsp;Debit/credit card numbers</p>
              <p>8.&nbsp;Age</p>
              <p>9.&nbsp;Password</p>
              <h2>
                <strong>How Do We Use The Information We Collect?</strong>
              </h2>
              <p>
                Any of the information we collect from you may be used in one of the following ways:
              </p>
              <p>
                1.&nbsp;To personalize your experience (your information helps us to better respond
                to your individual needs)
              </p>
              <p>
                2.&nbsp;To improve our website/app (we continually strive to improve our website/app
                offerings based on the information and feedback we receive from you)
              </p>
              <p>
                3.&nbsp;To improve customer service (your information helps us to more effectively
                respond to your customer service requests and support needs)
              </p>
              <p>4.&nbsp;To process transactions</p>
              <p>5.&nbsp;To administer a contest, promotion, survey or other site feature</p>
              <p>6.&nbsp;To send periodic emails</p>
              <h2>
                <strong>When does Solvea Use End User Information from Third Parties?</strong>
              </h2>
              <p>
                Solvea will collect End User Data necessary to provide the Solvea services to our
                customers.
              </p>
              <p>
                End users may voluntarily provide us with information they have made available on
                social media websites. If you provide us with any such information, we may collect
                publicly available information from the social media websites you have indicated.
                You can control how much of your information social media websites make public by
                visiting these websites and changing your privacy settings.
              </p>
              <h2>
                <strong>When does Solvea Use Customer Information from Third Parties?</strong>
              </h2>
              <p>
                We receive some information from the third parties when you contact us. For example,
                when you submit your email address to us to show interest in becoming a Solvea
                customer, we receive information from a third party that provides automated fraud
                detection services to Solvea. We also occasionally collect information that is made
                publicly available on social media websites. You can control how much of your
                information social media websites make public by visiting these websites and
                changing your privacy settings.
              </p>
              <h2>
                <strong>Do We Share the Information We Collect with Third Parties?</strong>
              </h2>
              <p>
                We share the information we collect, both personal and non-personal, with third
                parties only when it is necessary to provide our services or to enhance the
                functionality of our applications. This includes sharing with trusted third-party
                service providers who perform functions and provide services to us, such as hosting
                and maintaining our servers and the website/app, database storage and management,
                e-mail management, storage marketing, credit card processing, customer service, and
                fulfilling orders for products and services you may purchase through the
                website/app. These third parties are contractually bound to protect and use such
                information only for the purposes for which it was disclosed, consistent with this
                Privacy Policy.
              </p>
              <p>
                We may also share portions of our log file data, including IP addresses, for
                analytics purposes with trusted third parties such as web analytics partners,
                application developers, and ad networks. These partners use such information only to
                analyze how our services are used and to improve the functionality of our services.
                They are required to maintain the confidentiality of the data and are not permitted
                to share any information that can be used to identify individual users.
              </p>
              <p>
                In exceptional circumstances, we may disclose personal and non-personal information
                to government or law enforcement officials or private parties as we, in our sole
                discretion, believe necessary or appropriate in order to respond to claims, legal
                process (including subpoenas), to protect our rights and interests or those of a
                third party, the safety of the public or any person, to prevent or stop any illegal,
                unethical, or legally actionable activity, or to otherwise comply with applicable
                court orders, laws, rules, and regulations.
              </p>
              <h3>Third party details</h3>
              <h4>Facebook Pixel</h4>
              <p>
                In our helpdesk, we use Facebook pixel. Facebook pixel is an analytics tool that
                allows you to measure the effectiveness of your advertising by understanding the
                actions people take on your website. You can use the pixel to: Make sure your ads
                are shown to the right people. Facebook pixel may collect information from your
                device when you use the service. Facebook pixel collects information that is held in
                accordance with its Privacy Policy.
              </p>
              <h4>Google User Data</h4>
              <p>
                We confirm that we do not use, nor do we allow any third party to use, the data
                obtained through Google Workspace APIs to develop, improve, or train generalized AI
                or ML models. We ensure that no Google user data is transferred to third parties
                that do not directly contribute to the functionality of our application.
              </p>
              <h2>
                <strong>
                  Where and When is Information Collected from Customers and End Users?
                </strong>
              </h2>
              <p>
                <br />
                Solvea will collect personal information that you submit to us. We may also receive
                personal information about you from third parties as described above.
              </p>
              <h2>
                <strong>‍How Do We Use Your Email Address?</strong>
              </h2>
              <p>
                By submitting your email address on this website/app, you agree to receive emails
                from us. You can cancel your participation in any of these email lists at any time
                by clicking on the opt-out link or other unsubscribe option that is included in the
                respective email. We only send emails to people who have authorized us to contact
                them, either directly, or through a third party. We do not send unsolicited
                commercial emails, because we hate spam as much as you do. By submitting your email
                address, you also agree to allow us to use your email address for customer audience
                targeting on sites like Facebook, where we display custom advertising to specific
                people who have opted-in to receive communications from us. Email addresses
                submitted only through the order processing page will be used for the sole purpose
                of sending you information and updates pertaining to your order. If, however, you
                have provided the same email to us through another method, we may use it for any of
                the purposes stated in this Policy. Note: If at any time you would like to
                unsubscribe from receiving future emails, we include detailed unsubscribe
                instructions at the bottom of each email.‍
              </p>
              <h2>
                <strong>How Long Do We Keep Your Information?</strong>
              </h2>
              <p>
                We keep your information only so long as we need it to provide Solvea to you and
                fulfill the purposes described in this policy. This is also the case for anyone that
                we share your information with and who carries out services on our behalf. When we
                no longer need to use your information and there is no need for us to keep it to
                comply with our legal or regulatory obligations, we'll either remove it from our
                systems or depersonalize it so that we can't identify you.
              </p>
              <h2>
                <strong>‍How Do We Protect Your Information?</strong>
              </h2>
              <p>
                The security and confidentiality of your personal information is very important to
                Solvea. We have implemented commercially reasonable technical and organizational
                safeguards to appropriately protect your personal information against accidental,
                unauthorized, or unlawful access, use, loss, destruction or damage. Still, no system
                can be guaranteed to be 100% secure. If you have questions about the security of
                your personal information or if you have reason to believe that the personal
                information that we hold about you is no longer secure, please contact us
                immediately as described in this Privacy Policy.
              </p>
              <h2>
                <strong>Could My Information be Transferred to Other Countries?</strong>
              </h2>
              <p>
                Solvea is incorporated in Hong Kong. Information collected via our website, through
                direct interactions with you, or from use of our help services may be transferred
                from time to time to our offices or personnel, or to third parties, located
                throughout the world, and may be viewed and hosted anywhere in the world, including
                countries that may not have laws of general applicability regulating the use and
                transfer of such data. To the fullest extent allowed by applicable law, by using any
                of the above, you voluntarily consent to the trans-border transfer and hosting of
                such information. We will utilize appropriate safeguards governing the transfer and
                usage of your personal information.
              </p>
              <h2>
                <strong>Is the Information Collected Through the Solvea Service Secure?</strong>
              </h2>
              <p>
                We take precautions to protect the security of your information. We have physical,
                electronic, and managerial procedures to help safeguard, prevent unauthorized
                access, maintain data security, and correctly use your information. However, neither
                people nor security systems are foolproof, including encryption systems. In
                addition, people can commit intentional crimes, make mistakes or fail to follow
                policies. Therefore, while we use reasonable efforts to protect your personal
                information, we cannot guarantee its absolute security. If applicable law imposes
                any non-disclaimable duty to protect your personal information, you agree that
                intentional misconduct will be the standards used to measure our compliance with
                that duty.
              </p>
              <h2>
                <strong>‍Can I Update or Correct My Information?</strong>
              </h2>
              <p>
                The rights you have to request updates or corrections to the information Solvea
                collects depend on your relationship with Solvea. Personnel may update or correct
                their information as detailed in our internal company employment policies.
                <br />
              </p>
              <p>
                Customers have the right to request the restriction of certain uses and disclosures
                of personally identifiable information as follows. You can contact us in order to
                (1) update or correct your personally identifiable information, (2) change your
                preferences with respect to communications and other information you receive from
                us, or (3) delete the personally identifiable information maintained about you on
                our systems (subject to the following paragraph), by cancelling your account. Such
                updates, corrections, changes and deletions will have no effect on other information
                that we maintain, or information that we have provided to third parties in
                accordance with this Privacy Policy prior to such update, correction, change or
                deletion. To protect your privacy and security, we may take reasonable steps (such
                as requesting a unique password) to verify your identity before granting you profile
                access or making corrections. You are responsible for maintaining the secrecy of
                your unique password and account information at all times.
              </p>
              <p>
                You should be aware that it is not technologically possible to remove each and every
                record of the information you have provided to us from our system. The need to back
                up our systems to protect information from inadvertent loss means that a copy of
                your information may exist in a non-erasable form that will be difficult or
                impossible for us to locate. Promptly after receiving your request, all personal
                information stored in databases we actively use, and other readily searchable media
                will be updated, corrected, changed or deleted, as appropriate, as soon as and to
                the extent reasonably and technically practicable.
              </p>
              <p>
                <br />
                If you are an end user and wish to update, delete, or receive any information we
                have about you, you may do so by contacting the organization of which you are a
                customer. We will honor and support any instructions they provide us with respect to
                your personal information.
              </p>
              <h2>
                <strong>Personnel</strong>
              </h2>
              <p>
                If you are a Solvea worker or applicant, we collect information you voluntarily
                provide to us. We use the information collected for Human Resources purposes in
                order to administer benefits to workers and screen applicants.
                <br />
                You may contact us in order to (1) update or correct your information, (2) change
                your preferences with respect to communications and other information you receive
                from us, or (3) receive a record of the information we have relating to you. Such
                updates, corrections, changes and deletions will have no effect on other information
                that we maintain, or information that we have provided to third parties in
                accordance with this Privacy Policy prior to such update, correction, change or
                deletion.
              </p>
              <h2>
                <strong>‍Sale of Business</strong>
              </h2>
              <p>
                We reserve the right to transfer information to a third party in the event of a
                sale, merger or other transfer of all or substantially all of the assets of Solvea
                or any of its Corporate Affiliates (as defined herein), or that portion of Solvea or
                any of its Corporate Affiliates to which the Service relates, or in the event that
                we discontinue our business or file a petition or have filed against us a petition
                in bankruptcy, reorganization or similar proceeding, provided that the third party
                agrees to adhere to the terms of this Privacy Policy.
              </p>
              <h2>
                <strong>‍Affiliates</strong>
              </h2>
              <p>
                We may disclose information (including personal information) about you to our
                Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate"
                means any person or entity which directly or indirectly controls, is controlled by
                or is under common control with Solvea, whether by ownership or otherwise. Any
                information relating to you that we provide to our Corporate Affiliates will be
                treated by those Corporate Affiliates in accordance with the terms of this Privacy
                Policy.
              </p>
              <h2>
                <strong>‍Governing Law</strong>
              </h2>
              <p>
                This Privacy Policy is governed by the laws of Hong Kong without regard to its
                conflict of laws provision. You consent to the exclusive jurisdiction of the courts
                in connection with any action or dispute arising between the parties under or in
                connection with this Privacy Policy except for those individuals who may have rights
                to make claims under the EU-US and Swiss-US Privacy Shield framework.
              </p>
              <p>
                The laws of Hong Kong, excluding its conflicts of law rules, shall govern this
                Agreement and your use of the website/app. Your use of the website/app may also be
                subject to other local, state, national, or international laws.
              </p>
              <p>
                By using Solvea or contacting us directly, you signify your acceptance of this
                Privacy Policy. If you do not agree to this Privacy Policy, you should not engage
                with our website, or use our services. Continued use of the website, direct
                engagement with us, or following the posting of changes to this Privacy Policy that
                do not significantly affect the use or disclosure of your personal information will
                mean that you accept those changes.
              </p>
              <h2>
                <strong>‍Your Consent</strong>
              </h2>
              <p>
                We've updated our Privacy Policy to provide you with complete transparency into what
                is being set when you visit our site and how it's being used. By using our
                website/app, registering an account, or making a purchase, you hereby consent to our
                Privacy Policy and agree to its terms.
              </p>
              <h2>
                <strong>‍Links to Other Websites</strong>
              </h2>
              <p>
                This Privacy Policy applies only to the Services. The Services may contain links to
                other websites not operated or controlled by Solvea. We are not responsible for the
                content, accuracy or opinions expressed in such websites, and such websites are not
                investigated, monitored or checked for accuracy or completeness by us. Please
                remember that when you use a link to go from the Services to another website, our
                Privacy Policy is no longer in effect. Your browsing and interaction on any other
                website, including those that have a link on our platform, is subject to that
                website's own rules and policies. Such third parties may use their own cookies or
                other methods to collect information about you.
              </p>
              <h2>
                <strong>‍Advertising</strong>
              </h2>
              <p>
                This website/app may contain third party advertisements and links to third party
                sites. Solvea does not make any representation as to the accuracy or suitability of
                any of the information contained in those advertisements or sites and does not
                accept any responsibility or liability for the conduct or content of those
                advertisements and sites and the offerings made by the third parties.
              </p>
              <p>
                Advertising keeps Solvea and many of the websites and services you use free of
                charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as
                possible.
              </p>
              <p>
                Third party advertisements and links to other sites where goods or services are
                advertised are not endorsements or recommendations by Solvea of the third party
                sites, goods or services. Solvea takes no responsibility for the content of any of
                the ads, promises made, or the quality/reliability of the products or services
                offered in all advertisements.
              </p>
              <h2>
                <strong>Cookies for Advertising</strong>
              </h2>
              <p>
                These cookies collect information over time about your online activity on the
                website/app and other online services to make online advertisements more relevant
                and effective to you. This is known as interest-based advertising. They also perform
                functions like preventing the same ad from continuously reappearing and ensuring
                that ads are properly displayed for advertisers. Without cookies, it's really hard
                for an advertiser to reach its audience, or to know how many ads were shown and how
                many clicks they received. If you would prefer to not receive personalized ads based
                on your browser or device usage, you may generally express your opt-out preference
                to no longer receive tailored advertisements. Please note that you will continue to
                see advertisements, but they will no longer be tailored to your interests.{' '}
              </p>
              <p>
                To opt-out of interest-based advertising by participating companies in the following
                consumer choice mechanisms, please visit:
              </p>
              <p>
                -Digital Advertising Alliance (DAA)'s self-regulatory opt-out page
                (http://optout.aboutads.info/) and mobile application-based "AppChoices" download
                page (https://youradchoices.com/appchoices)
              </p>
              <p>
                -European Interactive Digital Advertising Alliance (EDAA)'s consumer opt-out page
                (http://youronlinechoices.eu)
              </p>
              <p>
                -Network Advertising Initiative (NAI)'s self-regulatory opt-out page (
                <a href="http://optout.networkadvertising.org/">
                  http://optout.networkadvertising.org/
                </a>
                ).
              </p>
              <p>
                In the mobile environment, most mobile operating systems offer device-based opt-out
                choices that are transmitted to companies providing interest-based advertising. To
                set an opt-out preference for a mobile device identifier (such as Apple's IDFA or
                Android's GAID), visit the device manufacturer's current choice instructions pages,
                or read more about sending signals to limit ad tracking for your operating system
                here: http://www.networkadvertising.org/mobile-choices.
              </p>
              <h2>
                <strong>Cookies</strong>
              </h2>
              <p>
                Solvea uses "Cookies" to identify the areas of our website that you have visited. A
                Cookie is a small piece of data stored on your computer or mobile device by your web
                browser. We use Cookies to enhance the performance and functionality of our
                website/app but are non-essential to their use. However, without these cookies,
                certain functionality like videos may become unavailable or you would be required to
                enter your login details every time you visit the website/app as we would not be
                able to remember that you had logged in previously. Most web browsers can be set to
                disable the use of Cookies. However, if you disable Cookies, you may not be able to
                access functionality on our website correctly or at all. We never place Personally
                Identifiable Information in Cookies.
              </p>
              <h2>
                <strong>Blocking and Disabling Cookies and Similar Technologies</strong>
              </h2>
              <p>
                Wherever you're located you may also set your browser to block cookies and similar
                technologies, but this action may block our essential cookies and prevent our
                website from functioning properly, and you may not be able to fully utilize all of
                its features and services. You should also be aware that you may also lose some
                saved information (e.g. saved login details, site preferences) if you block cookies
                on your browser. Different browsers make different controls available to you.
                Disabling a cookie or category of cookie does not delete the cookie from your
                browser, you will need to do this yourself from within your browser, you should
                visit your browser's help menu for more information.
              </p>
              <h2>
                <strong>‍Remarketing Services</strong>
              </h2>
              <p>
                We use remarketing services. What Is Remarketing? In digital marketing, remarketing
                (or retargeting) is the practice of serving ads across the internet to people who
                have already visited your website. It allows your company to seem like they're
                “following” people around the internet by serving ads on the websites and platforms
                they use most.
              </p>
              <h2>
                <strong>Payment Details</strong>
              </h2>
              <p>
                In respect to any credit card or other payment processing details you have provided
                us, we commit that this confidential information will be stored in the most secure
                manner possible.
              </p>
              <h2>
                <strong>‍Kids' Privacy</strong>
              </h2>
              <p>
                We do not address anyone under the age of 13. We do not knowingly collect personally
                identifiable information from anyone under the age of 13. If You are a parent or
                guardian and You are aware that Your child has provided Us with Personal Data,
                please contact Us. If We become aware that We have collected Personal Data from
                anyone under the age of 13 without verification of parental consent, We take steps
                to remove that information from Our servers.
              </p>
              <h2>
                <strong>‍Changes to Our Privacy Policy</strong>
              </h2>
              <p>
                We may change our Service and policies, and we may need to make changes to this
                Privacy Policy and its updated date so that they accurately reflect our Service and
                policies. Unless otherwise required by law, we will notify you (for example, through
                our Service) before we make changes to this Privacy Policy and give you an
                opportunity to review them before they go into effect. Then, if you continue to use
                the Service, you will be bound by the updated Privacy Policy. If you do not want to
                agree to this or any updated Privacy Policy, you can delete your account.{' '}
              </p>
              <h2>
                <strong>‍Third-Party Services</strong>
              </h2>
              <p>
                We may display, include or make available third-party content (including data,
                information, applications and other products services) or provide links to
                third-party websites or services ("Third- Party Services").
              </p>
              <p>
                You acknowledge and agree that Solvea shall not be responsible for any Third-Party
                Services, including their accuracy, completeness, timeliness, validity, copyright
                compliance, legality, decency, quality or any other aspect thereof. Solvea does not
                assume and shall not have any liability or responsibility to you or any other person
                or entity for any Third-Party Services.
              </p>
              <p>
                Third-Party Services and links thereto are provided solely as a convenience to you
                and you access and use them entirely at your own risk and subject to such third
                parties' terms and conditions.
              </p>
              <h2>
                <strong>‍Facebook Pixel</strong>
              </h2>
              <p>
                Facebook pixel is an analytics tool that allows you to measure the effectiveness of
                your advertising by understanding the actions people take on your website. You can
                use the pixel to: Make sure your ads are shown to the right people. Facebook pixel
                may collect information from your device when you use the service. Facebook pixel
                collects information that is held in accordance with its Privacy Policy.
              </p>
              <h2>
                <strong>‍Tracking Technologies</strong>
              </h2>
              <p>
                Cookies: We use Cookies to enhance the performance and functionality of our platform
                but are non-essential to their use. However, without these cookies, certain
                functionality like videos may become unavailable or you would be required to enter
                your login details every time you visit the platform as we would not be able to
                remember that you had logged in previously.
              </p>
              <h2>
                <strong>Information about General Data Protection Regulation (GDPR)</strong>
              </h2>
              <p>
                We may be collecting and using information from you if you are from the European
                Economic Area (EEA), and in this section of our Privacy Policy we are going to
                explain exactly how and why is this data collected, and how we maintain this data
                under protection from being replicated or used in the wrong way.
              </p>
              <h2>
                <strong>‍What is GDPR?</strong>
              </h2>
              <p>
                GDPR is an EU-wide privacy and data protection law that regulates how EU residents'
                data is protected by companies and enhances the control the EU residents have, over
                their personal data.
              </p>
              <p>
                The GDPR is relevant to any globally operating company and not just the EU-based
                businesses and EU residents. Our customers' data is important irrespective of where
                they are located, which is why we have implemented GDPR controls as our baseline
                standard for all our operations worldwide.
              </p>
              <h2>
                <strong>‍What is Personal Data?</strong>
              </h2>
              <p>
                Any data that relates to an identifiable or identified individual. GDPR covers a
                broad spectrum of information that could be used on its own, or in combination with
                other pieces of information, to identify a person. Personal data extends beyond a
                person's name or email address. Some examples include financial information,
                political opinions, genetic data, biometric data, IP addresses, physical address,
                sexual orientation, and ethnicity.
              </p>
              <p>The Data Protection Principles include requirements such as:</p>
              <p>
                1.&nbsp;Personal data collected must be processed in a fair, legal, and transparent
                way and should only be used in a way that a person would reasonably expect.
              </p>
              <p>
                2.&nbsp;Personal data should only be collected to fulfill a specific purpose and it
                should only be used for that purpose. Organizations must specify why they need the
                personal data when they collect it.
              </p>
              <p>
                3.&nbsp;Personal data should be held no longer than necessary to fulfill its
                purpose.
              </p>
              <p>
                4.&nbsp;People covered by the GDPR have the right to access their own personal data.
                They can also request a copy of their data, and that their data be updated, deleted,
                restricted, or moved to another organization.
              </p>
              <h2>
                <strong>‍Why is GDPR Important?</strong>
              </h2>
              <p>
                GDPR adds some new requirements regarding how companies should protect individuals'
                personal data that they collect and process. It also raises the stakes for
                compliance by increasing enforcement and imposing greater fines for breach. Beyond
                these facts it's simply the right thing to do. At Solvea we strongly believe that
                your data privacy is very important and we already have solid security and privacy
                practices in place that go beyond the requirements of this new regulation.
              </p>
              <h2>
                <strong>
                  Individual Data Subject's Rights - Data Access, Portability and Deletion
                </strong>
              </h2>
              <p>
                We are committed to helping our customers meet the data subject rights requirements
                of GDPR. Solvea processes or stores all personal data in fully vetted, DPA compliant
                vendors. We do store all conversation and personal data for up to 6 years unless
                your account is deleted. In which case, we dispose of all data in accordance with
                our Terms of Service and Privacy Policy, but we will not hold it longer than 60
                days.
              </p>
              <p>
                We are aware that if you are working with EU customers, you need to be able to
                provide them with the ability to access, update, retrieve and remove personal data.
                We got you! We've been set up as self service from the start and have always given
                you access to your data and your customers data. Our customer support team is here
                for you to answer any questions you might have about working with the API.
              </p>
              <h2>
                <strong>California Residents</strong>
              </h2>
              <p>
                The California Consumer Privacy Act (CCPA) requires us to disclose categories of
                Personal Information we collect and how we use it, the categories of sources from
                whom we collect Personal Information, and the third parties with whom we share it,
                which we have explained above.
              </p>
              <p>
                We are also required to communicate information about rights California residents
                have under California law. You may exercise the following rights:
              </p>
              <p>
                1.&nbsp;Right to Know and Access. You may submit a verifiable request for
                information regarding the: (1) categories of Personal Information we collect, use,
                or share; (2) purposes for which categories of Personal Information are collected or
                used by us; (3) categories of sources from which we collect Personal Information;
                and (4) specific pieces of Personal Information we have collected about you.
              </p>
              <p>
                2.&nbsp;Right to Equal Service. We will not discriminate against you if you exercise
                your privacy rights.
              </p>
              <p>
                3.&nbsp;Right to Delete. You may submit a verifiable request to close your account
                and we will delete Personal Information about you that we have collected.
              </p>
              <p>
                4.&nbsp;Request that a business that sells a consumer's personal data, not sell the
                consumer's personal data.
              </p>
              <p>
                If you make a request, we have one month to respond to you. If you would like to
                exercise any of these rights, please contact us.
              </p>
              <p>‍We do not sell the Personal Information of our users.</p>
              <p>For more information about these rights, please contact us.</p>
              <h2>
                <strong>California Online Privacy Protection Act (CalOPPA)</strong>
              </h2>
              <p>
                CalOPPA requires us to disclose categories of Personal Information we collect and
                how we use it, the categories of sources from whom we collect Personal Information,
                and the third parties with whom we share it, which we have explained above.
              </p>
              <p>‍CalOPPA users have the following rights:</p>
              <p>
                1.&nbsp;Right to Know and Access. You may submit a verifiable request for
                information regarding the: (1) categories of Personal Information we collect, use,
                or share; (2) purposes for which categories of Personal Information are collected or
                used by us; (3) categories of sources from which we collect Personal Information;
                and (4) specific pieces of Personal Information we have collected about you.
                <br />
                Right to Equal Service. We will not discriminate against you if you exercise your
                privacy rights.
              </p>
              <p>
                2.&nbsp;Right to Delete. You may submit a verifiable request to close your account
                and we will delete Personal Information about you that we have collected.
              </p>
              <p>
                3.&nbsp;Right to request that a business that sells a consumer's personal data, not
                sell the consumer's personal data.
                <br />
                If you make a request, we have one month to respond to you. If you would like to
                exercise any of these rights, please contact us.
              </p>
              <p>‍We do not sell the Personal Information of our users.</p>
              <p>For more information about these rights, please contact us.</p>
              <h2>
                <strong>‍Contact Us</strong>
              </h2>
              <p>
                Don't hesitate to contact us if you have any questions about this Privacy Policy, or
                wish to inquire about our personal information handling practices.{' '}
              </p>
              <p>Solvea Limited</p>
              <p>160 E Tasman Drive Suite 202 San Jose, CA, 95134 </p>
              <p>
                <br />
                Via Email:
                <a href="mailto:support@solvea.cx">support@solvea.cx</a>
              </p>
              <p>
                If you have an unresolved privacy or data use concern that we have not addressed
                satisfactorily, please contact our U.S.-based third party dispute resolution
                provider (free of charge) at{' '}
                <a href="https://feedback-form.truste.com/watchdog/request">
                  https://feedback-form.truste.com/watchdog/request
                </a>
                .
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default TermsAndCondition;
